INSERT INTO `restaurant` (
    `name`,
    `destId`,
    `address`,
    `telephone`,
    `description`,
    `additionInfo`,
    `demoImage`
) VALUES 
(
  1,
    'LES PHILOSOPHES',
    1,
    '28 rue Vieille du Temple Paris, 75 75004',
    '+33 1 48 87 49 64',
    'Les Philosophes is a cafe and brasserie with classic French cuisine and a few global influences on the menu. Our server here was super enthusiastic and friendly and made sure we had a great time! To start, we had the French onion soup, a savory, umami beef broth with caramelized onions, topped with croutons with melted Comte cheese on top. For our mains, the Les Philosophes salad came with lots of mixed vegetables (lettuce, greens, radicchio, endive, carrots, cucumber, tomatoes, olives, radishes, watermelon, avocado), slices of smoked duck breast, Pata Negra Bellota ham, and toasted sourdough bread topped with generous rounds of creamy goat cheese. The Grilled Wild Cod Fillet was served over white rice and vegetables and was on the bland side, but came with a super flavor coconut milk curry sauce.',
    'Soup, Chips & Meat',
    'https://s3-media0.fl.yelpcdn.com/bphoto/_hi1FXoi-Hz8Wf4m9BnKSQ/o.jpg,
    https://s3-media0.fl.yelpcdn.com/bphoto/_CSLDlGU_7L8YkDMPmcUMw/o.jpg,
    https://s3-media0.fl.yelpcdn.com/bphoto/ZFDRcmgjKcxz8qSmYOiCAA/o.jpg,
    https://s3-media0.fl.yelpcdn.com/bphoto/UnBVdVNRte25GM0mio6vIQ/o.jpg,
    https://s3-media0.fl.yelpcdn.com/bphoto/IxKvSheQyom-XDuyjhWOow/o.jpg,
    https://s3-media0.fl.yelpcdn.com/bphoto/ataoTKfISLKGMCxA8296Zw/o.jpg,
    https://s3-media0.fl.yelpcdn.com/bphoto/vVbgZY7TlO_mwDeEusgneA/o.jpg'
),
(
  2,
    'BEST BAGEL & COFFEE',
    6, -- Assuming destId 2 for a coffee shop category
    '225 W 35th St New York, NY 10001',
    '(212) 564-4409',
    'Fresh hand rolled bagels with variety of cream cheeses. Breakfast and lunch sandwiches, egg
platters, fresh salads, home made soups, premium coffee and drinks. We also do breakfast and
lunch catering. All baking done on premises.',
    'Bagels, Coffee & Tea, Breakfast & Brunch',
    'https://s3-media0.fl.yelpcdn.com/bphoto/Fl5qM-cluwUYcjP6KJ3AZQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/lxVsSydmg8H4IS8PlhHGIQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/lc5DYYBFkIUQJjW_YHAZ5A/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/Unibz9-p8grP0GR5ZacUWQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/G3l57K4Gexd4RXtaFXuPEw/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/Qb5oW7k4cKrLpC6EGajShw/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/aCrNRtcrdRAjZ4ckwLTZjg/o.jpg,'
),
(
  3,
    'FUJINOMIYA YAKISOBA GAKKAI',
    12, 
    '宮町4-23 Fujinomiya, 22 418-0067',
    '+81 544-22-5341',
    'Experience the authentic flavors of Fujinomiya at FUJINOMIYA YAKISOBA GAKKAI. Our culinary artisans craft traditional yakisoba dishes with precision and passion. Nestled in the heart of 宮町4-23, our restaurant invites you to savor the rich aroma and delightful taste of Japanese yakisoba',
    'Soba, Comfort Food',
    'https://s3-media0.fl.yelpcdn.com/bphoto/mQpQBsCGypoZInmLwiW8PQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/b2W3O7_NXOb4S2qx0CW3LA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/qN84PlnawNGwWHUrIdubUQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/3BGyXWsm5c8DZZ_kfRLJzQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/yvjxd90XYHIRaUTp3ItlnA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/s2K7insGkqFP3Tiadoksvg/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/Ni5qbFBNuC6pab1lVJhtNg/o.jpg'
),
(
  4,
    'KULATA ACADEMY CAFE',
    18,
    '127 Yulara Dr Yulara, NT 0872',
    '+61 2 8296 8010',
    'Cozy cafe with a diverse menu offering aromatic coffees, artisanal teas, delectable pastries, and savory delights. A warm and welcoming ambiance makes it a perfect spot for both solitude and social gatherings.',
    'Coffee & Tea, Autralian',
    'https://s3-media0.fl.yelpcdn.com/bphoto/U5BBq38FMkTAw-_9g07-aQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/wK1yfUpuFpT-yIO20enJkQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/gb16WhK34N7SFG15ApFU1g/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/NlE_MFM6NVu4bkOTFT9p6A/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/kXOESoNwdzs9mZ0RTWC7yg/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/24M6Lzy34r44Pa4kwqQk7g/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/DINa7ZRyCN-0_mkm4GeuHw/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/lF4lm3nxggwNpvfe5B4xNg/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/ctFCx4cwy1ImSNVxVow_Ww/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/kHsgYUnGlehGDawvU72GmQ/o.jpg'
),
(
  5,
    'ROMANTICA',
    23, -- Assuming destId 5 for a romantic restaurant category
    'Av. Hipólito Yrigoyen s/n Puerto Iguazú, N 3370',
    '+54 3757 42-0600',
    'Experience a romantic culinary journey at ROMANTICA. Nestled along Av. Hipólito Yrigoyen in Puerto Iguazú, our restaurant offers an intimate setting for unforgettable moments. Indulge in a menu curated for romance, featuring exquisite dishes and a selection of fine wines. With 3 glowing reviews, ROMANTICA is a destination where love and gastronomy come together. View our profile to discover more about our enchanting ambiance and culinary offerings.',
    'Argentine',
    'https://s3-media0.fl.yelpcdn.com/bphoto/TJzgWf_nfBxtHhH1q7uLYw/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/zkGM2fvvpTqsCk_01ZsPHA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/t0s6R1WsyeOK2ykfelHWeg/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/17OrlxcWgXiIGNoXMzpxXA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/k-zEW3XAuRDyGnitQtU7Dg/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/tIIfLosQBOoQgmyWmBwiqA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/tETjhPLcCT4Xi-WrfbY9Ig/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/3dkVAXBY8vCygqbueViupA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/U5PJS8YcR9chn6lX67u6bQ/o.jpg'
),
(
  6,
    'BÜGEL FABRIQUE DE BAGELS',
    40,
    '164 rue Crémazie Ouest Quebec City, QC G1R 1X7',
    '+1 418-523-7666',
    'Savor the authentic taste of handcrafted bagels at BÜGEL FABRIQUE DE BAGELS. Located at 164 rue Crémazie Ouest in Quebec City, our bagel shop offers a delightful assortment of freshly baked bagels with a variety of delectable toppings and spreads. Join the community of bagel enthusiasts with 85 glowing reviews, celebrating the unique flavors and quality of BÜGEL FABRIQUE DE BAGELS. View our profile for a sneak peek into our bagel-making process and discover why we are a favorite among locals and visitors alike.',
    'Breakfast & Brunch, Bagels',
    'https://s3-media0.fl.yelpcdn.com/bphoto/qDvOlqUVzUZjhdy1bFFEyA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/oVXNkyp_s6EzQpCQoFTULQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/wGY5eoSM9Uuocl7TUbUPKw/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/xGSh3Vp6ytt4oXm1qrtBuw/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/yjiMJZNoa7pc6PBr0iMhwA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/50AoJsCFHO2IKGr8VZqFVA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/q0Xme9bpNRUDW09SnrJAew/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/wF2-mss81Uc9X2mlpT7DLw/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/nCB-PhyjZUi63zUSfGhNkQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/Jbntt3m6xJebw5hO9Q3bUw/o.jpg'
),
(
  7,
    'Li River Cuisine Restaurant',
    42,
    'No.1 Shanhu North Road, Guilin, China',
    '+86 773 282 2881',
    'Discover the culinary delights of Li River Cuisine Restaurant, a hidden gem nestled in the heart of Guilin. With a prime location at No.1 Shanhu North Road, our restaurant offers a fusion of Chinese and Asian flavors that captivate the senses.',
    'Reservations, Seating, Serves Alcohol, Table Service',
    'https://img.restaurantguru.com/r7d0-Li-River-meat-2022-11-2.jpg,
    https://img.restaurantguru.com/r789-meat-Li-River-2022-11-5.jpg,
    https://img.restaurantguru.com/re55-meat-Li-River-2022-11-1.jpg,
    https://img.restaurantguru.com/rfe4-Li-River-meat-2022-11-5.jpg,
    https://img.restaurantguru.com/r4cb-Li-River-meat-2022-11.jpg,
    https://img.restaurantguru.com/rc56-meat-Li-River-2022-11.jpg,
    https://img.restaurantguru.com/r36e-seafood-Hongkong-2021-09.jpg'
),
(
  8,
    'TUNA AZUL',
    49, -- Assuming destId 7 for a seafood restaurant category
    'Calle Francisca Rodriguez 155 Puerto Vallarta, JAL 48380',
    '+52 322 178 0657',
    'Discover the ocean s bounty at TUNA AZUL, an exquisite seafood destination located on Calle Francisca Rodriguez in Puerto Vallarta. With a dedication to culinary excellence, our restaurant invites you to indulge in a seafood experience like no other.',
    'Seafood, Mexican',
    'https://s3-media0.fl.yelpcdn.com/bphoto/2TwMwrrGWAVbzlFUMCAP1w/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/pNyxmlZ9kXtPkmq5nLcu5g/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/g62RvhbMR4Pfy4Bux8rYJQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/HsjEfHd_hebNswkwM7gURQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/q9Uou3alyq4wOHauKwFdzQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/wOSPPoesKFUKtZnA2TYEBA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/pQ6ielsiyBkriRp480pDdA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/vy-WxvNX_Utali8PgcgYeQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/kRi_5rAj2mWlqLph5UIsUA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/4Fnw9mTLeA7ccVe6HvQN9g/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/J8nSdHpKtFMAKHPs5MUeTA/o.jpg'
),
(
  9,
    '773 NORTH',
    37, 
    '2749 Grand Island Blvd Grand Island, NY 14072',
    '(716) 773-6678',
    'Experience the flavors of Grand Island at 773 NORTH, a welcoming American restaurant located at 2749 Grand Island Blvd. Our commitment to exceptional dining is reflected in our diverse menu, offering something for everyone.',
    'New American, Bars, Breakfast & Lunch',
    'https://s3-media0.fl.yelpcdn.com/bphoto/JvrOV3OXVz3cw1TfBR77yg/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/0PfNotFk5LN144WL7yQ-TA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/d8xlY9B5REFOYap41CN2Zw/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/z0MVdIF37dY5mroNiaMDFA/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/bpwtlvToHwg-s-bPO8ik7A/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/DuuuwaV_H0BlM30C-tHKaw/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/KQdCsUELZS6YC1np-pc6Xg/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/DGbaPwHQYueVBABY8EI1Fg/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/vWr5YfMCvTZrBs1ThdjUNQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/BuN3zPBi33IPQLW0n-YoOQ/o.jpg,
https://s3-media0.fl.yelpcdn.com/bphoto/dETknOThsov3qoJh0lkc1g/o.jpg'
);

